/**
 * The drift gate — MAR-692.
 *
 * ## What went wrong that this exists to stop
 *
 * `src/lib/dashBrokerCatalog.ts` listed three broker operations while DASH had
 * fifteen, 598 commits behind, and nothing anywhere could see it. The pinned
 * manifest schema was missing `access: "spend"` — the one word an AI-backed
 * agent needs — for 323 commits. There was no copy of the artifact contract at
 * all. Every one of those was a comment saying "checked against DASH on
 * <date>", and a comment is not a mechanism.
 *
 * ## Why the gate that already existed did not catch it
 *
 * `scripts/check-dash-schema-drift.mjs` compares one schema against DASH's, and
 * it works — run by hand against a sibling checkout it reports the drift
 * correctly. It has two holes, and both are why the drift survived:
 *
 * 1. **It cannot run in CI.** It needs orchestratedash checked out beside this
 *    repo, and CI has no sibling, so it prints SKIPPED on every run that
 *    matters. A gate that only fires on the machine already looking is a
 *    reminder, not a gate. This one clones DASH at a pinned commit, so it runs
 *    everywhere.
 * 2. **It compares JSON-pointer PATHS, not values.** A new enum member is
 *    invisible to it — array elements contribute no pointer of their own — and
 *    `access: "spend"` is exactly a new enum member. So is a tightened
 *    `maxLength`, and so is a rewritten `description` that changes what a
 *    builder is told. This one compares values.
 *
 * ## What it compares, and how
 *
 * Four mirrors, each against the real source rather than against another copy:
 *
 * | mirror | checked against |
 * | --- | --- |
 * | `src/lib/dashBrokerCatalog.ts` operations | `allOperations()`, executed |
 * | `tests/fixtures/dash/broker-profiles.json` | `allOperations()` + `brokerProfileFor()`, executed |
 * | `src/lib/dashArtifactContract.ts` | `contracts/run-artifact.schema.json` |
 * | `tests/fixtures/dash/agent.manifest.v2.schema.json` | `contracts/agent.manifest.v2.schema.json` |
 *
 * The operation half is EXECUTED, not parsed. Twelve of DASH's fifteen
 * operations exist as no literal anywhere in its source — they are generated by
 * `aiProviders().map(...)` from ids assembled out of exported suffix constants.
 * A parser would have to re-implement that generation, which is a second copy of
 * the thing under test, drifting on its own schedule. Running DASH's module is
 * the only extraction with no second copy in it. See `dash-vocabulary.ts` for
 * why that is safe and what happens when it stops being.
 *
 * The `items_digest` mirror is checked by BEHAVIOUR: both DASH's
 * `fingerprintItems` and this repo's pasteable copy are run over the same items
 * and their hashes compared. Text that agrees in spelling can still disagree in
 * behaviour, and the failure mode here is silent — a drifted canonicalisation
 * turns every correct brief into an uncited one.
 *
 * ## Outcomes
 *
 *   exit 0            every mirror agrees
 *   exit 1            a mirror drifted, with the values that differ
 *   exit 1 + SKIPPED  orchestratedash is not available — the DEFAULT, and the
 *                     reversal that matters: the gate this replaces exited 0 here
 *   exit 0 + SKIPPED  same, but only under --allow-missing, which `pnpm verify`
 *                     passes and CI never does
 *
 * `--write` rewrites the mirrors it can rewrite (the two fixtures and the
 * artifact contract) instead of failing, for the re-sync commit. It never
 * rewrites `dashBrokerCatalog.ts`: deciding whether the emitter should now
 * *reach* a new operation is a judgement, and this script only insists that
 * somebody makes it.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
  extractDashVocabulary,
  locateDash,
  readDashContract,
  type DashVocabulary,
} from "./dash-vocabulary.js";
import {
  dashBrokerOperations,
  DASH_AI_OPERATION_SUFFIX,
  AI_PROVIDER_IDS,
} from "../src/lib/dashBrokerCatalog.js";
import {
  DASH_ITEMS_DIGEST_MIRROR_JS,
  DASH_RUN_ARTIFACT_SCHEMA,
  DASH_RUN_ARTIFACT_SCHEMA_COMMIT,
} from "../src/lib/dashArtifactContract.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FIXTURE_BROKER = path.join(repoRoot, "tests/fixtures/dash/broker-profiles.json");
const FIXTURE_MANIFEST = path.join(repoRoot, "tests/fixtures/dash/agent.manifest.v2.schema.json");
const ARTIFACT_MODULE = path.join(repoRoot, "src/lib/dashArtifactContract.ts");

const write = process.argv.includes("--write");
const explicit = process.argv.find((arg) => arg.startsWith("--dash="))?.slice("--dash=".length);
const allowMissing = process.argv.includes("--allow-missing");

const failures: string[] = [];
function fail(mirror: string, detail: string): void {
  failures.push(`  [${mirror}] ${detail}`);
}

/** Stable JSON, so a comparison is about content and never about key order. */
function canonical(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  if (value && typeof value === "object") {
    const entries = Object.keys(value as object)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`);
    return `{${entries.join(",")}}`;
  }
  return JSON.stringify(value) ?? "null";
}

/**
 * Every differing value between two documents, by JSON pointer.
 *
 * Values, not paths — the hole in `check-dash-schema-drift.mjs` this replaces.
 * A recursion that descends into arrays by index reports a new enum member,
 * which is precisely how `access: "spend"` stayed invisible for 323 commits.
 */
function valueDiffs(mine: unknown, theirs: unknown, pointer = ""): string[] {
  if (canonical(mine) === canonical(theirs)) return [];
  const bothObjects =
    mine !== null &&
    theirs !== null &&
    typeof mine === "object" &&
    typeof theirs === "object" &&
    Array.isArray(mine) === Array.isArray(theirs);
  if (!bothObjects) {
    return [
      `${pointer || "/"}\n      DASH:   ${truncate(canonical(theirs))}\n      mirror: ${truncate(canonical(mine))}`,
    ];
  }
  const keys = new Set([
    ...Object.keys(mine as object),
    ...Object.keys(theirs as object),
  ]);
  return [...keys]
    .sort()
    .flatMap((key) =>
      valueDiffs(
        (mine as Record<string, unknown>)[key],
        (theirs as Record<string, unknown>)[key],
        `${pointer}/${key}`,
      ),
    );
}

function truncate(value: string, max = 160): string {
  return value.length > max ? `${value.slice(0, max)}…` : value;
}

/**
 * Run this repo's pasteable `items_digest` mirror and return its hash.
 *
 * Evaluated rather than read, because the property under test is behavioural.
 * The snippet is written for a built agent and opens with a `node:crypto`
 * import, which a `Function` body cannot carry — so the import line is dropped
 * and `createHash` supplied from this process. That substitution is the only
 * edit made to it, and it is the reason the check can be behavioural at all.
 */
function runMirrorFingerprint(items: unknown[]): string {
  const body = DASH_ITEMS_DIGEST_MIRROR_JS.split("\n")
    .filter((line) => !line.startsWith("import "))
    .join("\n");
  const factory = new Function(
    "createHash",
    `${body}\nreturn fingerprintItems;`,
  ) as (hash: typeof createHash) => (items: unknown[]) => string;
  return factory(createHash)(items);
}

async function main(): Promise<void> {
  const dashPath = locateDash(explicit);
  if (!dashPath) {
    /*
     * A missing sibling is a failure by default, and `--allow-missing` is the
     * one place it is not.
     *
     * The old gate exited 0 on a missing sibling, everywhere, which is how 598
     * commits of drift went unreported: CI has no sibling, so the only machine
     * that ran the check on every push was the one machine that always said
     * SKIPPED. Reversing the default is the whole point. `pnpm verify` passes
     * `--allow-missing` so a contributor without orchestratedash checked out can
     * still verify their own work; CI passes nothing, having cloned DASH at the
     * pinned commit first, so the skip that mattered is now impossible.
     */
    const message =
      "orchestratedash could not be found, so nothing about drift was proven.\n" +
      "  Pass --dash=<path>, set ORCHESTRATEDASH_PATH, or check it out beside this repo.\n" +
      "  CI clones it at the commit pinned in tests/fixtures/dash/broker-profiles.json.";
    if (allowMissing) {
      console.log(`[dash-vocab] SKIPPED — ${message}`);
      process.exit(0);
    }
    console.error(`[dash-vocab] SKIPPED, and that is a FAILURE — ${message}`);
    process.exit(1);
  }

  const dash: DashVocabulary = await extractDashVocabulary(dashPath);
  const fixture = JSON.parse(readFileSync(FIXTURE_BROKER, "utf-8")) as Record<string, unknown>;
  const pinned = String(fixture.source_commit ?? "");

  console.log(`[dash-vocab] orchestratedash: ${dashPath}`);
  console.log(`[dash-vocab] pinned commit:   ${pinned}`);
  console.log(`[dash-vocab] checkout HEAD:   ${dash.head_commit ?? "(not a git checkout)"}`);
  if (dash.head_commit && dash.head_commit !== pinned) {
    /*
     * Provenance, not a verdict. Content is what is judged: a checkout at a
     * different commit whose broker files are byte-identical to the pin is not
     * drift, and saying otherwise would fail a developer for having master
     * checked out. CI clones the pin exactly, so this line never appears there.
     */
    console.log(
      "[dash-vocab] NOTE: the checkout is not at the pinned commit. The comparison below is " +
        "against what is on disk, which is the honest thing to report.",
    );
  }

  // 1. The operation catalogue the emitter builds capability ids from.
  const mirrored = dashBrokerOperations().map((operation) => ({
    id: operation.id,
    connection_provider: operation.connection_provider,
    access: operation.access,
    required_scopes: [...operation.required_scopes].sort(),
  }));
  const operationDiffs = valueDiffs(mirrored, dash.operations);
  if (operationDiffs.length > 0) {
    fail(
      "src/lib/dashBrokerCatalog.ts",
      `the mirrored operation catalogue disagrees with DASH's allOperations():\n` +
        operationDiffs.map((entry) => `    ${entry}`).join("\n") +
        `\n    DASH has ${dash.operations.length} operations; this mirror has ${mirrored.length}.` +
        `\n    Fix the array by hand, then decide separately whether dashOperationsForComponent()` +
        `\n    should now REACH anything new — that judgement is why this file is not auto-written.`,
    );
  }

  // 2. The id suffixes the AI capability block is assembled from.
  const suffixDiffs = valueDiffs(
    { ...DASH_AI_OPERATION_SUFFIX },
    dash.operation_id_suffixes,
  );
  if (suffixDiffs.length > 0) {
    fail(
      "src/lib/dashBrokerCatalog.ts",
      "DASH_AI_OPERATION_SUFFIX no longer spells DASH's operation ids:\n" +
        suffixDiffs.map((entry) => `    ${entry}`).join("\n"),
    );
  }

  const providerDiffs = valueDiffs([...AI_PROVIDER_IDS], dash.ai_provider_ids);
  if (providerDiffs.length > 0) {
    fail(
      "src/lib/dashBrokerCatalog.ts",
      "AI_PROVIDER_IDS no longer matches DASH's AI_PROVIDER_IDS:\n" +
        providerDiffs.map((entry) => `    ${entry}`).join("\n"),
    );
  }

  // 3. The broker fixture the cross-repo round-trip test is grounded in.
  const rebuiltFixture = {
    ...fixture,
    ai_provider_ids: dash.ai_provider_ids,
    operation_id_suffixes: dash.operation_id_suffixes,
    profiles: dash.profiles,
    operations: dash.operations,
  };
  const fixtureDiffs = valueDiffs(
    {
      ai_provider_ids: fixture.ai_provider_ids,
      operation_id_suffixes: fixture.operation_id_suffixes,
      profiles: fixture.profiles,
      operations: fixture.operations,
    },
    {
      ai_provider_ids: dash.ai_provider_ids,
      operation_id_suffixes: dash.operation_id_suffixes,
      profiles: dash.profiles,
      operations: dash.operations,
    },
  );
  if (fixtureDiffs.length > 0) {
    if (write) {
      writeFileSync(FIXTURE_BROKER, `${JSON.stringify(rebuiltFixture, null, 2)}\n`);
      console.log("[dash-vocab] rewrote tests/fixtures/dash/broker-profiles.json");
    } else {
      fail(
        "tests/fixtures/dash/broker-profiles.json",
        "the pinned broker facts disagree with DASH's:\n" +
          fixtureDiffs.map((entry) => `    ${entry}`).join("\n") +
          "\n    Re-sync with: pnpm dash:vocab:check --write",
      );
    }
  }

  // 4. The artifact contract the brief hands a builder, byte for byte.
  const canonicalArtifact = JSON.parse(
    readDashContract(dashPath, "run-artifact.schema.json"),
  ) as unknown;
  const artifactDiffs = valueDiffs(DASH_RUN_ARTIFACT_SCHEMA, canonicalArtifact);
  if (artifactDiffs.length > 0) {
    if (write) {
      rewriteArtifactModule(dashPath, dash.head_commit ?? pinned);
      console.log("[dash-vocab] rewrote src/lib/dashArtifactContract.ts");
    } else {
      fail(
        "src/lib/dashArtifactContract.ts",
        "the copied run-artifact contract is not DASH's:\n" +
          artifactDiffs.map((entry) => `    ${entry}`).join("\n") +
          "\n    Re-sync with: pnpm dash:vocab:check --write" +
          "\n    Then READ the diff: a new kind, a new required member or a tightened ceiling" +
          "\n    changes what §9 must tell a builder to produce.",
      );
    }
  }
  if (DASH_RUN_ARTIFACT_SCHEMA_COMMIT !== pinned && !write) {
    fail(
      "src/lib/dashArtifactContract.ts",
      `DASH_RUN_ARTIFACT_SCHEMA_COMMIT is ${DASH_RUN_ARTIFACT_SCHEMA_COMMIT} but the broker ` +
        `fixture pins ${pinned}. The two mirrors must name one commit or a reader cannot tell ` +
        "which DASH this build agrees with.",
    );
  }

  // 5. The manifest schema, now compared by value rather than by pointer.
  const canonicalManifest = JSON.parse(
    readDashContract(dashPath, "agent.manifest.v2.schema.json"),
  ) as unknown;
  const pinnedManifest = JSON.parse(readFileSync(FIXTURE_MANIFEST, "utf-8")) as unknown;
  const manifestDiffs = valueDiffs(pinnedManifest, canonicalManifest);
  if (manifestDiffs.length > 0) {
    if (write) {
      writeFileSync(FIXTURE_MANIFEST, readDashContract(dashPath, "agent.manifest.v2.schema.json"));
      console.log("[dash-vocab] rewrote tests/fixtures/dash/agent.manifest.v2.schema.json");
    } else {
      fail(
        "tests/fixtures/dash/agent.manifest.v2.schema.json",
        "the pinned manifest schema is not DASH's:\n" +
          manifestDiffs.map((entry) => `    ${entry}`).join("\n") +
          "\n    Re-sync with: pnpm dash:vocab:check --write",
      );
    }
  }

  // 6. The items_digest canonicalisation, compared by BEHAVIOUR.
  const fingerprintModule = (await import(
    pathToFileURL(path.join(dashPath, "lib/brief/fingerprint.ts")).href
  )) as { fingerprintItems: (items: readonly unknown[]) => string };
  const probe = [
    { headline: "One", source_url: "https://a.example/feed", item_url: "https://a.example/1" },
    { headline: "Two — with an em dash, a \"quote\" and a , comma" },
    { headline: "Three", source_url: "https://b.example/feed" },
  ];
  const theirs = fingerprintModule.fingerprintItems(probe as never);
  const ours = runMirrorFingerprint(probe);
  if (theirs !== ours) {
    fail(
      "src/lib/dashArtifactContract.ts",
      "DASH_ITEMS_DIGEST_MIRROR_JS no longer computes DASH's fingerprint:\n" +
        `      DASH:   ${theirs}\n      mirror: ${ours}\n` +
        "    This is the silent one. A brief built from the drifted copy validates, imports, and\n" +
        "    renders with EVERY citation withheld, because DASH recomputes the digest over the\n" +
        "    list it holds and refuses to join on a mismatch. Re-copy the three functions from\n" +
        "    orchestratedash lib/brief/fingerprint.ts by hand.",
    );
  }

  if (failures.length > 0) {
    console.error("\n[dash-vocab] DRIFT — the MCP's copy of DASH's vocabulary is out of date.\n");
    console.error(failures.join("\n\n"));
    console.error(
      "\n  Confirm the source is DASH master before re-syncing — orchestratedash is read-only\n" +
        "  from here, and a copy taken from an in-flight branch pins something never released.\n",
    );
    process.exit(1);
  }

  console.log(
    `[dash-vocab] OK — ${dash.operations.length} operations, ${dash.profiles.length} broker ` +
      `profiles, the run-artifact contract and the items_digest fingerprint all agree with DASH.`,
  );
}

/** Rebuild the artifact-contract module around a fresh copy of DASH's schema. */
function rewriteArtifactModule(dashPath: string, commit: string): void {
  const source = readFileSync(ARTIFACT_MODULE, "utf-8").replace(/\r\n/g, "\n");
  const schema = readDashContract(dashPath, "run-artifact.schema.json")
    .replace(/\r\n/g, "\n")
    .trimEnd();
  const openMarker = "export const DASH_RUN_ARTIFACT_SCHEMA: Readonly<Record<string, unknown>> =";
  const closeMarker = "\n\n/**\n * The `items_digest` canonicalisation";
  const open = source.indexOf(openMarker);
  const close = source.indexOf(closeMarker);
  if (open < 0 || close < 0) {
    throw new Error(
      "src/lib/dashArtifactContract.ts no longer has the markers --write rewrites between. " +
        "Re-copy the schema by hand rather than letting this script guess at the file.",
    );
  }
  const head = source
    .slice(0, open)
    .replace(
      /export const DASH_RUN_ARTIFACT_SCHEMA_COMMIT = "[0-9a-f]*";/,
      `export const DASH_RUN_ARTIFACT_SCHEMA_COMMIT = "${commit}";`,
    );
  writeFileSync(
    ARTIFACT_MODULE,
    `${head}${openMarker}\n  ${schema};${source.slice(close)}`,
  );
}

await main();
